version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sitemanager
      MYSQL_USER: bitrixuser
      MYSQL_PASSWORD: bitrixpassword
      MYSQL_ROOT_HOST: "%"  
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"  
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  web:
    build: .
    ports:
      - "80:80"
    environment:
      - PHP_TZ=Europe/Moscow
      - APACHE_DOCUMENT_ROOT=/var/www/html
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini  
    depends_on:
      db:
        condition: service_healthy  
    restart: always

volumes:
  db_data: