version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sitemanager
      MYSQL_USER: bitrixuser
      MYSQL_PASSWORD: bitrixpassword
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  web:
    build: .
    ports:
      - "80:80"
    environment:
      - PHP_TZ=Europe/Moscow
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    restart: always

volumes:
  db_data: